"""Generate the website's TypeScript and CSS brand contract from brandkit data."""

from __future__ import annotations

import json
from pathlib import Path

from brandkit.logo import current_stroke_paths
from brandkit.spec import BRAND, COLORS, DIMENSIONS, TYPOGRAPHY
from brandkit.typography import ensure_plus_jakarta_extrabold, outline_text


_HEADER = "// Generated by brandkit.web_contract.py. Do not edit manually.\n"


def _camel_case(value: str) -> str:
    head, *tail = value.split("_")
    return head + "".join(part.title() for part in tail)


def _typescript(value: object) -> str:
    return json.dumps(value, ensure_ascii=True, indent=2, sort_keys=True) + " as const"


def _font_stack(name: str) -> str:
    typography = TYPOGRAPHY[name]
    families = (typography["family"], *typography["fallbacks"])
    return ", ".join(f'"{family}"' for family in families)


def _token_module() -> str:
    colors = {_camel_case(name): value for name, value in COLORS.items()}
    typography = {
        name: {
            "family": values["family"],
            "stack": _font_stack(name),
            "weights": list(values.get("weights", ())),
        }
        for name, values in TYPOGRAPHY.items()
        if name in {"display", "body", "technical"}
    }
    spacing = [8, 16, 24, 32, 48]
    return (
        _HEADER
        + "\n"
        + f"export const NEW_WAVE_COLORS = {_typescript(colors)};\n\n"
        + f"export const NEW_WAVE_TYPOGRAPHY = {_typescript(typography)};\n\n"
        + f"export const NEW_WAVE_SPACING = {_typescript(spacing)};\n\n"
        + f"export const NEW_WAVE_BRAND_NAME = {json.dumps(BRAND['name'], ensure_ascii=True)} as const;\n"
    )


def _logo_module() -> str:
    font_path = ensure_plus_jakarta_extrabold()
    wordmark = outline_text("NEW WAVE IT", font_path)
    heritage = outline_text(BRAND["heritage_line"], font_path)
    geometry = {
        "viewBox": {"width": 360, "height": 120},
        "icon": dict(DIMENSIONS["logo"]["master_viewbox"]),
        "minimumDigitalWidth": dict(DIMENSIONS["logo"]["minimum_digital_width"]),
    }
    path_payload = {
        "d": wordmark.d,
        "advance": wordmark.advance,
        "unitsPerEm": wordmark.units_per_em,
    }
    heritage_payload = {
        "d": heritage.d,
        "advance": heritage.advance,
        "unitsPerEm": heritage.units_per_em,
    }
    return (
        _HEADER
        + "\n"
        + f"export const STANDARD_CURRENT_STROKES = {_typescript(list(current_stroke_paths('standard')))};\n\n"
        + f"export const MICRO_CURRENT_STROKES = {_typescript(list(current_stroke_paths('micro')))};\n\n"
        + f"export const WORDMARK_PATH = {_typescript(path_payload)};\n\n"
        + f"export const HERITAGE_PATH = {_typescript(heritage_payload)};\n\n"
        + f"export const NEW_WAVE_LOGO_GEOMETRY = {_typescript(geometry)};\n"
    )


def _brand_css() -> str:
    color_lines = "\n".join(
        f"  --nw-{name.replace('_', '-')}: {value};" for name, value in COLORS.items()
    )
    spacing_lines = "\n".join(
        f"  --nw-space-{index}: {value}px;" for index, value in enumerate((8, 16, 24, 32, 48), start=1)
    )
    return (
        "/* Generated by brandkit.web_contract.py. Do not edit manually. */\n"
        ":root {\n"
        f"{color_lines}\n"
        f"  --nw-font-display: {_font_stack('display')};\n"
        f"  --nw-font-body: {_font_stack('body')};\n"
        f"  --nw-font-technical: {_font_stack('technical')};\n"
        f"{spacing_lines}\n"
        "  --nw-radius-control: 6px;\n"
        "  --nw-radius-panel: 8px;\n"
        "}\n"
    )


def write_web_contract(project_root: Path) -> tuple[Path, Path]:
    """Write deterministic browser-facing tokens, paths, and CSS to a project root."""
    source_root = project_root / "src"
    brand_root = source_root / "brand"
    styles_root = source_root / "styles"
    brand_root.mkdir(parents=True, exist_ok=True)
    styles_root.mkdir(parents=True, exist_ok=True)

    tokens_path = brand_root / "tokens.ts"
    logo_paths_path = brand_root / "logoPaths.ts"
    tokens_path.write_text(_token_module(), encoding="utf-8", newline="\n")
    logo_paths_path.write_text(_logo_module(), encoding="utf-8", newline="\n")
    (styles_root / "brand.css").write_text(_brand_css(), encoding="utf-8", newline="\n")
    return tokens_path, logo_paths_path
