// Generated by brandkit.web_contract.py. Do not edit manually.

export const NEW_WAVE_COLORS = {
  "cloudWhite": "#F7FAFB",
  "continuityGreen": "#62BE68",
  "currentNavy": "#101E2D",
  "deepCurrent": "#09131D",
  "mistGray": "#E8EFF1",
  "pureWhite": "#FFFFFF",
  "signalCyan": "#31C6CF",
  "slate": "#526271",
  "tideBlue": "#317B92"
} as const;

export const NEW_WAVE_TYPOGRAPHY = {
  "body": {
    "family": "Inter",
    "stack": "\"Inter\", \"system-ui\", \"sans-serif\"",
    "weights": [
      400,
      500,
      600,
      700
    ]
  },
  "display": {
    "family": "Plus Jakarta Sans",
    "stack": "\"Plus Jakarta Sans\", \"Inter\", \"system-ui\", \"sans-serif\"",
    "weights": [
      600,
      700,
      800
    ]
  },
  "technical": {
    "family": "IBM Plex Mono",
    "stack": "\"IBM Plex Mono\", \"ui-monospace\", \"monospace\"",
    "weights": [
      400,
      500,
      600
    ]
  }
} as const;

export const NEW_WAVE_SPACING = [
  8,
  16,
  24,
  32,
  48
] as const;

export const NEW_WAVE_BRAND_NAME = "New Wave IT" as const;
